<script src="{{asset('template/js/jquery-3.2.1.min.js')}}"></script>
<script src="{{asset('template/js/popper.js')}}"></script>
<script src="{{asset('template/js/bootstrap.min.js')}}"></script>
<script src="{{asset('template/vendors/nice-select/js/jquery.nice-select.min.js')}}"></script>
<script src="{{asset('template/vendors/isotope/isotope-min.js')}}"></script>
<script src="{{asset('template/vendors/owl-carousel/owl.carousel.min.js')}}"></script>
<script src="{{asset('template/js/jquery.ajaxchimp.min.js')}}"></script>
<script src="{{asset('template/js/jquery.counterup.min.js')}}"></script>
<script src="{{asset('template/js/jquery.waypoints.min.js')}}"></script>
<script src="{{asset('template/js/mail-script.js')}}"></script>
<script src="{{asset('template/js/custom.js')}}"></script>
{{--JS mask--}}
<script src="{{asset('js/jquery.mask.js')}}"></script>